spring:
  datasource:
    username: ${DB_USER:rootUser}
    password: ${DB_PASSWORD:password}
    url: ${DB_URL:jdbc:mysql://:3306/demodb}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect

